packages:
  - "apps/*"
  - "packages/*"

trustLockfile: true

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  contentlayer2: true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  "@types/react": "^19.0.10"
  "@types/react-dom": "^19.0.4"
  postcss: "8.5.10"
  posthog-js>dompurify: "3.4.2"
  protobufjs: "7.5.6"
  "@microsoft/tsdoc-config>ajv": "6.14.0"
  mdx-bundler>uuid: "14.0.0"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - contentlayer2
  - core-js
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
