// This file is generated by scripts/generate-admin-bridge.mjs.
// Do not edit manually.

import type { ComponentType } from "react"

export const ADMIN_MODULE_AVAILABLE = false as const

export async function loadAdminDashboardModule(): Promise<ComponentType | null> {
  return null
}
