// This file is generated by scripts/generate-admin-bridge.mjs.
// Do not edit manually.

import type { ComponentType } from "react"

export const ADMIN_MODULE_AVAILABLE = false as const

export interface AdminMenuItem {
  id: string
  label: string
  iconKey: string
  href: string
  children?: AdminMenuItem[]
}

export interface AdminRegistry {
  menu: AdminMenuItem[]
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  pages: { id: string; path: string; component: ComponentType<any> }[]
}

export async function loadAdminModule(): Promise<{
  Shell: ComponentType | null
  registry: AdminRegistry | null
}> {
  return { Shell: null, registry: null }
}
